const clients= [
        { client_id: 1, first_name: 'María', last_name: 'González', email: 'maria@gonza.com', phone: '987-654-3210', address: 'Avenida Secundaria 456', postal_code: '44970', neighborhood: 'Norte', city: 'Guadalajara'},
        { client_id: 2, first_name: 'Pedro', last_name: 'Ramírez', email: 'pedro@rami.com', phone:'555-123-4567', address: 'Calle Comercial 789', postal_code: '64268', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 3, first_name: 'Luis', last_name: 'Mora', email: 'luis@mora.com', phone: '225-173-4967', address: 'Calle Ánimas 123', postal_code: '77500', neighborhood:'Norte', city:'Cancún'},
        { client_id: 4, first_name: 'Leticia', last_name: 'Domínguez', email: 'leticia@domin.com', phone: '255-183-8567', address: 'Calle Naranjos 234', postal_code: '68016', neighborhood:'Sur', city:'Oaxaca'},
        { client_id: 5, first_name: 'Misael', last_name: 'Córtes', email: 'misael@cortes.com', phone: '155-123-4567', address: 'Calle Guanabana 345', postal_code: '01269', neighborhood:'Norte', city:'Ciudad de México'},
        { client_id: 6, first_name: 'Sara', last_name: 'Córtes', email: 'sara@cortes.com', phone: '905-123-7867', address: 'Calle 20 de Noviembre 384', postal_code: '64268', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 7, first_name: 'Jaime', last_name: 'Herrera', email: 'jaime@herrera.com', phone: '565-173-4397', address: 'Calle Celestial 345', postal_code: '44970', neighborhood:'Norte', city:'Guadalajara'},
        { client_id: 8, first_name: 'Oswaldo', last_name: 'Torres', email: 'oswaldo@torres.com', phone: '535-123-4067', address: 'Calle Carranza 456', postal_code: '77500', neighborhood:'Sur', city:'Cancún'},
        { client_id: 9, first_name: 'Ana', last_name: 'Flores', email: 'ana@flores.com', phone: '655-623-9567', address: 'Calle cerezos 567', postal_code: '68016', neighborhood:'Norte', city:'Oaxaca'},
        { client_id: 10, first_name: 'Julio', last_name: 'Morales', email: 'julio@morales.com', phone: '785-343-4590', address: 'Avenida Ignacio 678', postal_code: '01269', neighborhood:'Sur', city:'Ciudad de México'},
        { client_id: 11, first_name: 'Delmer', last_name: 'Hernández', email: 'delmer@hernandez.com', phone: '987-123-3457', address: 'Avenida Lázaro Cárdenas 789', postal_code: '44970', neighborhood:'Norte', city:'Guadalajara'},
        { client_id: 12, first_name: 'Deysi', last_name: 'Vázquez', email: 'deysi@vazquez.com', phone: '125-123-6867', address: 'Calle Carranza 890', postal_code: '64160', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 13, first_name: 'Daniela', last_name: 'Cabrera', email: 'daniela@cabrera.com', phone: '345-123-2897', address: 'Calle Almendras 901', postal_code: '77500', neighborhood:'Sur', city:'Cancún'},
        { client_id: 14, first_name: 'Anibal', last_name: 'Hernández', email: 'anibal@hernan.com', phone: '115-123-9087', address: 'Calle Agua Santa 001', postal_code: '68023', neighborhood:'Norte', city:'Oaxaca'},
        { client_id: 15, first_name: 'Mariana', last_name: 'Alvarado', email: 'mariana@alvarado.com', phone: '565-783-4567', address: 'Calle Agua Santa 002', postal_code: '01180', neighborhood:'Norte', city:'Ciudad de México'},
        { client_id: 16, first_name: 'Bertha', last_name: 'Alvarez', email: 'bertha@alvarez.com', phone: '675-123-3427', address: 'Calle Flores 002', postal_code: '44910', neighborhood:'Sur', city:'Guadalajara'},
        { client_id: 17, first_name: 'Azucena', last_name: 'Baños', email: 'azucena@baños.com', phone: '678-123-4327', address: 'Calle Bosques 023', postal_code: '64160', neighborhood:'Norte', city:'Monterrey'},
        { client_id: 18, first_name: 'Daniela', last_name: 'Bocanegra', email: 'daniela@bocanegra.com', phone: '905-733-4567', address: 'Calle Ébano 203', postal_code: '77500', neighborhood:'Sur', city:'Cancún'},
        { client_id: 19, first_name: 'Patricia', last_name: 'Caballero', email: 'patricia@caballero.com', phone: '456-123-4567', address:  'Calle Ruiz Cortinez 377', postal_code: '68023', neighborhood:'Norte', city:'Oaxaca'},
        { client_id: 20, first_name: 'Alondra', last_name: 'Campos', email: 'alondra@campos.com', phone: '990-123-4567', address: 'Avenida Coatepec 275', postal_code: '01180', neighborhood:'Sur', city:'Ciudad de México'},
        { client_id: 21, first_name: 'Jesús', last_name: 'Carrillo', email: 'jesus@carrillo.com', phone: '889-123-4567', address: 'Avenida Coatepec 267', postal_code: '44910', neighborhood:'Norte', city:'Guadalajara'},
        { client_id: 22, first_name: 'Ana', last_name: 'Cordova', email: 'ana@cordova.com', phone: '555-478-4567', address: 'Avenida Revolución 789', postal_code: '64229', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 23, first_name: 'Mirna', last_name: 'Galindo', email: 'mirna@galindo.com', phone: '555-304-4567', address: 'Avenida Revolución 456', postal_code: '77500', neighborhood:'Norte', city:'Cancún'},
        { client_id: 24, first_name: 'Nadia', last_name: 'Trujillo', email: 'nadia@trujillo.com', phone: '555-123-7829', address: 'Calle Bosque 111', postal_code: '68013', neighborhood:'Sur', city:'Oaxaca'},
        { client_id: 25, first_name: 'Rosario', last_name: 'Peregrino', email: 'rosario@peregrino.com', phone: '865-123-4567', address: 'Calle Guanabana 222', postal_code: '01729', neighborhood:'Norte', city:'Ciudad de México'},
        { client_id: 26, first_name: 'Nancy', last_name: 'García', email: 'nancy@garcia.com', phone: '222-123-4567', address: 'Calle Agua Dulce 333', postal_code: '44270', neighborhood:'Sur', city:'Guadalajara'},
        { client_id: 27, first_name: 'Abel', last_name: 'Ramírez', email: 'abel@ramirez.com', phone: '333-123-4567', address: 'Calle Agua Dulce 444', postal_code: '64229', neighborhood:'Norte', city:'Monterrey'},
        { client_id: 28, first_name: 'Elvira', last_name: 'Jacinto', email: 'elvira@jacinto.com', phone: '558-123-4567', address: 'Calle Comercial 555', postal_code: '77500', neighborhood:'Sur', city:'Cancún'},
        { client_id: 29, first_name: 'Virginia', last_name: 'López', email: 'virginia@lopez.com', phone: '999-123-4567', address: 'Calle Comercial 666', postal_code: '68013', neighborhood:'Norte', city:'Oaxaca'},
        { client_id: 30, first_name: 'Julio', last_name: 'Torres', email: 'julio@torres.com', phone: '666-123-4567', address: 'Calle 20 de noviembre 777', postal_code: '01729', neighborhood:'Sur', city:'Ciudad de México'},
        { client_id: 31, first_name: 'Clara', last_name: 'Corpus', email: 'clara@corpus.com', phone: '555-567-4567', address: 'Calle 20 de noviembre 888', postal_code: '44270', neighborhood:'Norte', city:'Guadalajara'},
        { client_id: 32, first_name: 'Luis', last_name: 'Mendoza', email: 'luis@mendoza.com', phone: '555-090-4567', address: 'Calle Ébano 999', postal_code: '64186', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 33, first_name: 'Blanca', last_name: 'Brindis', email: 'blanca@brindis.com', phone: '555-123-3478', address: 'Calle Ébano 100', postal_code: '77500', neighborhood:'Norte', city:'Cancún'},
        { client_id: 34, first_name: 'Felipe', last_name: 'Reyes', email: 'felipe@reyes.com', phone: '555-123-2345', address: 'Calle Celestial 200', postal_code: '68028', neighborhood:'Sur', city:'Oaxaca'},
        { client_id: 35, first_name: 'Maribel', last_name: 'Reyes', email: 'maribel@reyes.com', phone: '555-123-0967', address: 'Calle Celestial 300', postal_code: '01125', neighborhood:'Norte', city:'Ciudad de México'},
        { client_id: 36, first_name: 'Melchor', last_name: 'Solano', email: 'melchor@solano.com', phone: '777-123-4567', address: 'Avenida Xalapa 400', postal_code: '44160', neighborhood:'Sur', city:'Guadalajara'},
        { client_id: 37, first_name: 'Sergio', last_name: 'Rendón', email: 'sergio@rendon.com', phone: '885-123-4567', address: 'Avenida Xalapa 500', postal_code: '64186', neighborhood:'Norte', city:'Monterrey'},
        { client_id: 38, first_name: 'Nayeli', last_name: 'Ramos', email: 'nayeli@ramos.com', phone: '555-123-2938', address: 'Calle Arquitectos 600', postal_code: '77500', neighborhood:'Sur', city:'Cancún'},
        { client_id: 39, first_name: 'Rodolfo', last_name: 'Sandoval', email: 'rodolfo@sandoval.com', phone: '555-409-4567', address: 'Calle Arquitectos 756', postal_code: '68028', neighborhood:'Sur', city:'Oaxaca'},
        { client_id: 40, first_name: 'Hector', last_name: 'Torres', email: 'hector@torres.com', phone: '555-123-3947', address: 'Calle Ámericas 943', postal_code: '01125', neighborhood:'Norte', city:'Ciudad de México'},
        { client_id: 41, first_name: 'Leticia', last_name: 'Cruz', email: 'leticia@cruz.com', phone: '555-123-2495', address: 'Avenida Ámericas 989', postal_code: '64186', neighborhood:'Sur', city:'Monterrey'},
        { client_id: 42, first_name: 'Isabel', last_name: 'Gallegos', email: 'isabel@gallegos.com', phone: '555-395-4567', address: 'Calle Cerezos 459', postal_code: '64186', neighborhood:'Norte', city:'Monterrey'}
    
];

console.table(clients);