const saleProducts = [
    { sale_id: 1, name_product: 'Leche', amount: 10 },
    { sale_id: 2, name_product: 'Huevo', amount: 1 },
    { sale_id: 3, name_product: 'Arroz', amount: 2 },
    { sale_id: 4, name_product: 'Frijol', amount: 3 },
    { sale_id: 5, name_product: 'Sopa', amount: 1 },
    { sale_id: 6, name_product: 'Huevo', amount: 8 },
    { sale_id: 7, name_product: 'Leche', amount: 2 },
    { sale_id: 8, name_product: 'Aceite', amount: 6 },
    { sale_id: 9, name_product: 'Frijol', amount: 5 },
    { sale_id: 10, name_product: 'Café', amount: 2 },
    { sale_id: 11, name_product: 'Harina', amount: 1 },
    { sale_id: 12, name_product: 'Galletas Marías', amount: 2 },
    { sale_id: 13, name_product: 'Toallas sanitarias', amount: 1 },
    { sale_id: 14, name_product: 'Papel higiénico', amount: 2 },
    { sale_id: 15, name_product: 'Café', amount: 1 },
    { sale_id: 16, name_product: 'Leche', amount: 5 },
    { sale_id: 17, name_product: 'Papel higiénico', amount: 1 },
    { sale_id: 18, name_product: 'Aceite', amount: 2 },
    { sale_id: 19, name_product: 'Mantequilla', amount: 1 },
    { sale_id: 20, name_product: 'Toallas sanitarias', amount: 1 },
    { sale_id: 21, name_product: 'Papel higiénico', amount: 4 },
    { sale_id: 22, name_product: 'Pasta de dientes', amount: 3 },
    { sale_id: 23, name_product: 'Palomitas', amount: 1 },
    { sale_id: 24, name_product: 'Pasta de dientes', amount: 2 },
    { sale_id: 25, name_product: 'Mayonesa', amount: 1 },
    { sale_id: 26, name_product: 'Palomitas', amount: 2 },
    { sale_id: 27, name_product: 'Vinagre', amount: 1 },
    { sale_id: 28, name_product: 'Jabón de tocador', amount: 3 },
    { sale_id: 29, name_product: 'Harina', amount: 1 },
    { sale_id: 30, name_product: 'Cigarros', amount: 3 },
    { sale_id: 31, name_product: 'Sopa', amount: 4 },
    { sale_id: 32, name_product: 'Jabón de tocador', amount: 1 },
    { sale_id: 33, name_product: 'Queso', amount: 2 },
    { sale_id: 34, name_product: 'Yakult', amount: 1 },
    { sale_id: 35, name_product: 'Mantequilla', amount: 1 },
    { sale_id: 36, name_product: 'Galletas Marías', amount: 2 },
    { sale_id: 37, name_product: 'Arroz', amount: 3 },
    { sale_id: 38, name_product: 'Huevo', amount: 1 },
    { sale_id: 39, name_product: 'Cigarros', amount: 2 },
    { sale_id: 40, name_product: 'Queso', amount: 1 }
];

console.table(saleProducts);
